### PR TITLE
Report error if a file glob doesn't match anything

### LINKED ISSUE #62: Uploading artifacts that don't exist doesn't cause an error
I mistakenly didn't spell an artifact file correctly in the `files` argument to action-automatic-releases.  I expected that there would be an error but instead, nothing happened and no assets were uploaded.

### PR DESCRIPTION
**Pull request by eyal0**
This fixes #62

I didn't test this.

### CODE REVIEW

**Comment by marvinpinto** [comment]
I think it might be reasonable to report that no files were found with the glob. I would prefer `info` instead of error though. 

Could probably reduce that diff down to something like:

```diff
   const paths = await globby(files);
+  if (paths.length === 0) {
+    core.info(`Could not find any release assets to upload`);
+  }
```

How does this behave in situations where a repo does not specify files to upload? I'm theoretically on board with adding this but my maintenance here is limited and so I will need this to be as bullet proof as possible (with tests, etc).

If you don't have the time for that I totally understand :+1:

**Comment by eyal0** [comment]
The code that you suggest, if there are no files to upload, will report that error (or info).  That's not good.

The code as I wrote it would not report an error because, if there are no globs specified then we'll never enter the loop.  This is a good behavior and consistent with other unix tools.

I based my PR on the behavior of `bash` CLI, which is that if a glob is specified but matches nothing, an error is reported.  I think that people would expect that consistency with tools that they've already used.

Also, I think that `info` is insufficient because it's too easy to not notice those.  It would be easy to accidentally make releases that have missing assets.

**Comment by Margen67** [comment]
Can you make this into an option?

**Comment by eyal0** [comment]
BTW, are there instructions on how to use this repo in a fork?  I know that this repo backs multiple different GitHub actions.  How can I compile my own version and test this?

(It's not great that GitHub only allows one action per repo.  If they didn't have that limitation, you could put all the actions into this one repo and save all the trouble in publishing.)

**Comment by marvinpinto** [comment]
Darn, I didn't realize what hitting the "merge branch" button did in GitHub. Could you rebase this again and remove my weirdo "Merge branch 'master' into patch-1" commit? I'll merge this as-is after that :+1:

**Comment by eyal0** [comment]
Done.

**Pull request merged**
