### PR TITLE
Update Github Runner Node version and deprecate set-output

### PR DESCRIPTION
**Pull request by maggie44**
Update Runner Node version. Resolves: https://github.com/marvinpinto/actions/issues/543
Remove deprecated set-output command. Resolves: https://github.com/marvinpinto/actions/issues/544
[bump @actions/core from 1.4.0 to 1.10.0](https://github.com/marvinpinto/actions/pull/546/commits/4c7a8e059f62336d64cf50dd471cd6afc424529a) to resolve set-output issues in dependencies.

### CODE REVIEW

**Comment by ldeluigi** [comment]
LGTM

**Comment by francesco-ballarin** [comment]
Is it possible that are a couple more occurrences of set-output to be changed, at least in the automatic releases action? 
I see two warnings about set-output in my CI logs, and I am unsure if they are the ones that @maggie0002 already found. Indeed, the calls changed in this PR seem to be associated to the CI of this repo, but not in the actions themselves.

For instance, looking at the automatic releases action, I can see set-output mentioned in
https://github.com/marvinpinto/action-automatic-releases/blob/master/dist/index.js
I have no experience in how this javascript file is generated, but I guess two calls to set-output may come in from
https://github.com/marvinpinto/actions/blob/master/packages/automatic-releases/src/main.ts#L319
https://github.com/marvinpinto/actions/blob/master/packages/automatic-releases/src/main.ts#L320

@maggie0002 @marvinpinto looking forward to your feedback!

**Comment by maggie0002** [comment]
@francesco-ballarin, the index.js you are pointing to is the built output of this repo. Once this PR is merged, it will build and deploy new code to replace index.js. 

setOutput is different to set-output. 

If you have tested it and finding some issues then let us know, but it is best to describe how you have tested this and the issues you are running in to with it.

**Comment by francesco-ballarin** [comment]
Thanks @maggie0002 

Unfortunately I don't know how to test this, at least until @marvinpinto merges this PR.
The two warnings I am mentioning come from the currently released version of the automatic releases action.

My suspicion that `setOutput` calls the deprecated `set-output` stems from this line https://github.com/actions/toolkit/blob/b36e704/packages/core/src/core.ts#L199

**Comment by maggie0002** [comment]
@francesco-ballarin, wow you really dug deep, good job.

The point you're referencing though is an external package. I can't imagine it would make a difference here as there are no signs of set-output in the build output and the issues seems to relate to use of set-output with stdout. If it does though, then it would be a pull request on the other repo to fix it rather than here (and then a package bump here). It shouldn't impact displaying of the error message either way and I don't think will impact the package. 

@marvinpinto will be looking at all these before merging too, and will certainly know best from having built this particular build setup.

**Comment by francesco-ballarin** [comment]
@marvinpinto @maggie0002 FYI, about `core.setOuput`: https://github.com/actions/toolkit/issues/1218, which would probably require #535 to be merged

**Comment by maggie0002** [comment]
@francesco-ballarin I added the package bump here, you try testing this out.

**Comment by francesco-ballarin** [comment]
@marvinpinto how can I test this? I typically use https://github.com/marvinpinto/action-automatic-releases, but my understanding is that such a repository will get updated only after this PR is merged.

**Comment by maggie0002** [comment]
This branch has the packages built for each in it: https://github.com/maggie0002/actions/commit/1c38253e5516e60baa8df5b62217f1dfbc476715

You would have to push each folder to a new repo, like this one for the automatic-releases: https://github.com/maggie0002/actions/tree/1c38253e5516e60baa8df5b62217f1dfbc476715/packages/automatic-releases

Then when that folder is in a repo by itself and in the root you would swap the code to point to your test package:

```diff
- - uses: "marvinpinto/action-automatic-releases@latest"
+ - uses: "francesco-ballarin/action-automatic-releases@latest"
```

**Comment by francesco-ballarin** [comment]
Thanks @maggie0002! I can confirm that on my project this PR fixes both deprecation warnings.

CI run before this PR: https://github.com/fem-on-colab/fem-on-colab/actions/runs/3385955348 (notice: 3 warnings)
Temporary commit changing the action to your repo: https://github.com/fem-on-colab/fem-on-colab/commit/d6a34cb85c03a27de31b4c37cfedfc109f04e95a
CI run after this PR: https://github.com/fem-on-colab/fem-on-colab/actions/runs/3385937266 (notice: 0 warnings)

@marvinpinto looking forward to seeing this PR merged soon!

**Comment by AlessandroMinunnoNOV** [comment]
Hi,

Do you have any idea when this PR will be merged and released?

Thanks

**Comment by ldeluigi** [comment]
It seems that this repo is a bit abandoned

**Comment by triplef** [comment]
@marvinpinto any chance getting this merged? 🙏 

Otherwise can anyone suggest an alternative to "GitHub Automatic Releases" that is still being maintained?

**Comment by mjlshen** [comment]
I've been using https://github.com/softprops/action-gh-release, which is still actively maintained

**Review by dimaqq — APPROVED** [review]

**Comment by dimaqq** [comment]
@marvinpinto 🙏🏻

**Comment by PtPrashantTripathi** [comment]
Hi @marvinpinto , I came across your repository and found a venrablity in it. 
> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

However, I saw that @maggie44 has already created a pull request to fix the issue. 

I have tested the fix and can confirm that it works well. I think it would be great if you could review and merge the pull request. 

This will help other users who depend on your repository. Thank you for maintaining this valuable resource!

**Comment by SimonDarksideJ** [comment]
Any likelihood of this PR being merged any time soon, the fixes look good and match what I've implemented in my other repos.  Time is running out before these deprecated features will be turned off @marvinpinto .

**Comment by glensc** [comment]
Before you write yet another "ping" like noise here, see that the user is actually active from their profile page:
- https://github.com/marvinpinto

**Comment by wiverson** [comment]
FWIW, the profile shows no activity in over a month.

**Comment by SimonDarksideJ** [comment]
So I see, which could effectively state that this specific project/repo is now dead, but a ping does email the user to "check-in"
Odd since this is one of the three projects "recommended" by the GitHub Actions team as a replacement for their deprecated Releases action. 

Shame

**Comment by sbe-arg** [comment]
hey @maggie44 I'm a new maintainer I can merge prs. https://github.com/marvinpinto/actions/actions/runs/5248984690 
The tests after merge where broken can you open a new pr to address these ? If I open a pr we get stuck again as I cannot self merge. 

all worlflows need actions/checkout and actions/cache bumped to version v3 as v2 uses set-output and node12 wich both are deprecated
https://github.com/marvinpinto/actions/tree/master/.github/workflows

**Comment by Enase** [comment]
@sbe-arg As I understand, eslint fails because of commit message. Any ideas of how to fix? force push? O_o

**Comment by Enase** [comment]
@sbe-arg take a look https://github.com/marvinpinto/actions/pull/642/files, I will describe the details

**Comment by bbimber** [comment]
@sbe-arg or others: thank you for those who updated this. However, I am missing something. This was merged and the change are in this monorepo (marvinpinto/actions). However, the auto-generated repo does not have those changes:

https://github.com/marvinpinto/action-automatic-releases
https://github.com/marvinpinto/action-automatic-releases/blob/latest/action.yml

My code is pointing to "uses: "marvinpinto/action-automatic-releases@latest"

Is there a way to use a version of this with the updated code?

Thanks in advance for any help.

**Comment by sbe-arg** [comment]
The problem is the credentials that replicate the  code builds are expired/invalid and only @marvinpinto can recreate them.

If anyone wants to build and open prs in the other repo ill peer review and merge.

Since this blocker I have moved my workflows to this action https://github.com/marketplace/actions/simple-tags-and-releases

Hard to maintain this project without the keys or admin repo access.

**Comment by bbimber** [comment]
@sbe-arg: ok, thanks. does simple-tags-and-releases have any ability to delete an existing tag? the main reason we've been using this is to auto-generate a 'latest' tag, overwriting the previous one.

**Comment by sbe-arg** [comment]
Not yet but probably is easy work on the prerrelease front as the github cli auto manages the latest tag

**Pull request merged**
