### PR TITLE
chore: skip commit verification + bump @babel/* dependencies

### PR DESCRIPTION
**Pull request by Enase**
fixes https://github.com/marvinpinto/actions/pull/546

### CODE REVIEW

**Comment by sbe-arg** [comment]
thanks!

**Comment by Enase** [comment]
> remote: Invalid username or password.
Investigating...

**Comment by sbe-arg** [comment]
I'm assuming a PAT token expired? GITHUB_SUPER_TOKEN? @marvinpinto  otherwise there is no fix if we can't cross push. We need admin access to edit the child repos to allow this master repo to have actions native permissions instead of PAT.

looks like a block without marvin

**Comment by Enase** [comment]
@sbe-arg @marvinpinto yes, it's a blocker, I cannot help here

**Comment by sbe-arg** [comment]
emailed @marvinpinto  with details if there is no input we can probably fork everything in a new org with a few maintainers

**Comment by sbe-arg** [comment]
Because the cross repository sharing permissions are broken and can only be fixed by @marvinpinto we are limited in how to implement the builds.

I don't want to re engineer the flows much.
And this pr is sort of asking for a big re restructure now #675 

I asked @Enase to disable linting wich is breaking the checks after each pr and each push to main

**Comment by Enase** [comment]
@sbe-arg no reason to disable linters, just fix the issues and that's it. see the very last comment on PR

**Comment by sbe-arg** [comment]
Id prefer if we disable the linters for the commits altogether

**Comment by Enase** [comment]
@sbe-arg If you disable the commit linter, it will prevent the `automatic-releases` plugin from [generating the changelog](https://github.com/marvinpinto/actions/blob/master/packages/automatic-releases/src/main.ts#L202) correctly. it uses [`conventional-commits-parser`](https://github.com/marvinpinto/actions/blob/master/packages/automatic-releases/src/main.ts#L5)

**Comment by Enase** [comment]
@sbe-arg as a result we need to deal with changelog generation. release data wont include "random" commits, see
https://github.com/marvinpinto/actions/releases

**Pull request merged**
